/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as LoteSlugRouteImport } from './routes/lote.$slug'
import { Route as ApiPublicSkalepayWebhookRouteImport } from './routes/api/public/skalepay-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoteSlugRoute = LoteSlugRouteImport.update({
  id: '/lote/$slug',
  path: '/lote/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSkalepayWebhookRoute =
  ApiPublicSkalepayWebhookRouteImport.update({
    id: '/api/public/skalepay-webhook',
    path: '/api/public/skalepay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/lote/$slug': typeof LoteSlugRoute
  '/api/public/skalepay-webhook': typeof ApiPublicSkalepayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/lote/$slug': typeof LoteSlugRoute
  '/api/public/skalepay-webhook': typeof ApiPublicSkalepayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/lote/$slug': typeof LoteSlugRoute
  '/api/public/skalepay-webhook': typeof ApiPublicSkalepayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/checkout' | '/lote/$slug' | '/api/public/skalepay-webhook'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/checkout' | '/lote/$slug' | '/api/public/skalepay-webhook'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/lote/$slug'
    | '/api/public/skalepay-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  LoteSlugRoute: typeof LoteSlugRoute
  ApiPublicSkalepayWebhookRoute: typeof ApiPublicSkalepayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lote/$slug': {
      id: '/lote/$slug'
      path: '/lote/$slug'
      fullPath: '/lote/$slug'
      preLoaderRoute: typeof LoteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/skalepay-webhook': {
      id: '/api/public/skalepay-webhook'
      path: '/api/public/skalepay-webhook'
      fullPath: '/api/public/skalepay-webhook'
      preLoaderRoute: typeof ApiPublicSkalepayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  LoteSlugRoute: LoteSlugRoute,
  ApiPublicSkalepayWebhookRoute: ApiPublicSkalepayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
